### ISSUE TITLE
无法动态修改校验规则,v-verify属性不生效

### ISSUE THREAD

**Issue by anyclub** [joinyi/v-verify#3]
使用场景为:
先由一个选择框,通过选择证件类型(身份证\护照等).
然后第二个输入框,根据之前选择框的类型,实现不同的校验规则

v-verify属性是由父组件通过props传递到相应子组件,
通过vue-dev工具,发现起对应属性v-verify已经更改,但是页面上的实际校验规则并未被更改

**Comment by joinyi** [comment]
我尝试根据v-verify的参数变化重新初始化验证器，发现在update钩子中`vnode`和`oldVnode`中dirctives 数据一样所以暂时还没有发现watch `v-verify`参数变化的好办法

**Comment by anyclub** [comment]
我有一个暂时解决的方案,因为不知道其他代码的细节,所以那个方案应该可以进一步优化.
方便用一个其他的方式交流么

53881706企鹅

**Comment by joinyi** [comment]
好的
